// NON-ERRORS
const CREATED = 201;

// ERRORS
const VALIDATION_ERROR = 400; // Bad Request
const DOCUMENT_NOT_FOUND_ERROR = 404; // Not Found
const MONGOOSE_ERROR = 500; // Internal Server Error
const UNAUTHORIZED_ERROR = 401; // Unauthorized
const FORBIDDEN_ERROR = 403; // Forbidden
const NOT_FOUND_ERROR = 404; // Not Found
const CONFLICT_ERROR = 409; // Conflict
const INTERNAL_SERVER_ERROR = 500; // Internal Server Error

module.exports = {
  CREATED,
  VALIDATION_ERROR,
  DOCUMENT_NOT_FOUND_ERROR,
  MONGOOSE_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  CONFLICT_ERROR,
  INTERNAL_SERVER_ERROR,
};
